Error: Fix tabs messing up indentation.
This fixes an edge case where the '^~~'
was not aligned with the actual offending
character(s) because of tabs before the characters.

Signed-off-by: Itai-Nelken <itainelken@gmail.com>